// export { default as Categories } from "./categories";
// export { default as Header } from "./header";
export { default as Navbar } from "./navbar";
export { default as MetaData } from "./metadata";
// export { default as Products } from "./products";
// export { default as Alert } from "./alert";
// export { default as Checkout } from "./checkout";
// export { default as Footer } from "./footer";
// export { default as Blog } from "./blog";
// export { default as Homepage } from "./homepage";
// export { default as DetailBlog } from "./blog/detail";
// export { default as DetailProduct } from "./products/detail";
// export { default as User } from "./user";
// export { default as Address } from "./user/address";
// export { default as Profile } from "./user/profile";
// export { default as Payment } from "./user/payment";
// export { default as Login } from "./auth";
// export { default as Register } from "./auth/register";
// export { default as Cart } from "./cart";
// export { default as Order } from "./order";
// export { default as MyOrder } from "./order/myorder";
// export { default as SubHeader } from "./subheader";
